[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1

[[main]]
    identifier = "store"
    name = "Store"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://portal.christitus.com/e3532423-ee96-4ebd-b228-7bb9f9b1d9b2"
    weight = 5

[[main]]
    name = "Members"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    url = "https://portal.christitus.com"
    weight = 2

[[main]]
    name = "Sections"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 3

[[main]]
    name = "Android"
    url = "/categories/android"
    parent = "Sections"

[[main]]
    name = "Linux"
    url = "/categories/linux"
    parent = "Sections"

[[main]]
    name = "MacOS"
    url = "/categories/macos"
    parent = "Sections"

[[main]]
    name = "Networking"
    url = "/categories/networking"
    parent = "Sections"

[[main]]
    name = "Windows"
    url = "/categories/windows"
    parent = "Sections"

[[main]]
    name = "Social"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 4

[[main]]
    name = "Github"
    url = "https://github.com/ChrisTitusTech"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Twitch"
    url = "https://twitch.tv/christitustech"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Twitter"
    url = "https://twitter.com/christitustech"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "YouTube Channels"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 6
    
[[main]]
    name = "Chris Titus Tech"
    url = "https://youtube.com/c/ChrisTitusTech"
    hrefTargetBlank = true
    parent = "YouTube Channels"

[[main]]
    name = "Titus Tech Talk"
    url = "https://youtube.com/c/ChrisTitusTechStreams"
    hrefTargetBlank = true
    parent = "YouTube Channels"

[[main]]
    name = "Chris Titus Crypto"
    url = "https://www.youtube.com/channel/UC31U-ll2Q1niJ2QIhKlfpZA"
    hrefTargetBlank = true
    parent = "YouTube Channels"