[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1

[[members]]
    identifier = "members"
    name = "Members"
    url = "https://portal.christitus.com"
    weight = 3

[[main]]
    name = "Remote Support"
    post = ""
    pre = "<i class='fa fa-road'></i>"
    url = "https://download.teamviewer.com/download/TeamViewerQS.exe"
    weight = 9

